FCV_DutchLadyMail/FCV_DutchLadyMail/Controllers/DistributorsController.cs
using System;
using ClosedXML.Excel;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FCV_DutchLadyMail_Model.Models;
using PagedList;
using LinqToExcel;
using System.Data;
using System.Data.SqlClient;
using System.Data.OleDb;
using System.Data.Entity.Validation;
using System.Net.Mail;
using System.Web.UI;  
using System.Web.UI.WebControls;
using FCV_DutchLadyMail_Model.Attribute;
using FCV_DutchLadyMail_Model.Common;
using System.IO;

namespace FCV_DutchLadyMail.Controllers
{
    public class DistributorsController : BaseController
    {
        private MassMailsDbContext db = new MassMailsDbContext();
        //
        // GET: /Distributors/

        public ActionResult Index(string sortOrder, int page = 1, int pageSize = 10 )
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CodeSortParm = sortOrder == "Code" ? "date_desc" : "code";

            ViewBag.lstRegion = db.Regions.ToList();
            ViewBag.Region = new SelectList(db.Regions.ToList(), "ID", "Name");
            var data = from a in db.Distributors
                       join b in db.Regions on a.Region equals b.ID
                       select new DistributorsView {
                           ID=a.ID,
                           Region=a.Region,
                           Name = a.Name,
                           Code = a.Code,
                           AdminMail = a.AdminMail,
                           SEMail = a.SEMail,
                           AcMail = a.AcMail,
                           ManagerMail = a.ManagerMail,
                           Address = a.Address,
                           State = a.State,                     
                           Regions = b
                       };


            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(s => s.Name);
                    break;
                case "code":
                    data = data.OrderBy(s => s.Code);
                    break;
                case "code_desc":
                    data = data.OrderByDescending(s => s.Code);
                    break;
                default:
                    data = data.OrderBy(s => s.Name);
                    break;
            }
            var _list = data.ToList();
            return View(_list);
        }
        public ActionResult GetListSearch(string selectednumbers, string paramJson, DistributorModel NPP, int? page = 1)
        {
            ViewBag.lstRegion = db.Regions.ToList();
            ViewBag.Region = new SelectList(db.Regions.ToList(), "ID", "Name");
            var data = from a in db.Distributors
                       join b in db.Regions on a.Region equals b.ID
                       select new DistributorsView
                       {

                           ID = a.ID,
                           Region = a.Region,
                           Name = a.Name,
                           Code = a.Code,
                           AdminMail = a.AdminMail,
                           SEMail = a.SEMail,
                           AcMail = a.AcMail,
                           ManagerMail = a.ManagerMail,
                           State = a.State,
                           Address = a.Address,
                           Regions = b
                       };

            if (!String.IsNullOrEmpty(NPP.Code))
            {
                data = data.Where(s => s.Code.ToString().ToUpper().Contains(NPP.Code.ToUpper()));
            }
            if (!String.IsNullOrEmpty(NPP.Name))
            {
                data = data.Where(s => s.Name.ToString().ToUpper().Contains(NPP.Name.ToUpper()));
            }
            if (!String.IsNullOrEmpty(NPP.SEMail))
            {
                data = data.Where(s => s.SEMail.ToString().ToUpper().Contains(NPP.SEMail.ToUpper()));

            }
            if (!String.IsNullOrEmpty(NPP.ManagerMail))
            {
                data = data.Where(s => s.ManagerMail.ToString().ToUpper().Contains(NPP.ManagerMail.ToUpper()));
            }
            if (!String.IsNullOrEmpty(NPP.AcMail))
            {
                data = data.Where(s => s.AcMail.ToString().ToUpper().Contains(NPP.AcMail.ToUpper()));
            }
            if (!String.IsNullOrEmpty(NPP.AdminMail))
            {
                data = data.Where(s => s.AdminMail.ToString().ToUpper().Contains(NPP.AdminMail.ToUpper()));
            }
            if (!String.IsNullOrEmpty(NPP.Address))
            {
                data = data.Where(s => s.Address.ToString().ToUpper().Contains(NPP.Address.ToUpper()));
            }
            var tempData = data;
            List<DistributorsView> lst = new List<DistributorsView>();

            if (selectednumbers == "")
                lst = data.ToList();
            else
            {
                string[] idR = selectednumbers.Split(',');
                lst = lst.ToList();
                foreach (string item in idR)
                {
                    int id = Convert.ToInt32(item);
                    tempData = data.Where(s => s.Region == id);
                    lst.AddRange(tempData);
                }
            }
            return PartialView("_GetListSearchDis", lst.ToList());
        }
   
        public ActionResult ExportExcel()
        {
            // Step 1 - get the data from database
            var data = db.Distributors.ToList();

            var gv = new GridView();
            gv.DataSource = data;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View();

        }
        [HttpPost]
        public ActionResult ImportExcel()
        {
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase FileUpload = files[0];
            List<string> data = new List<string>();
            if (FileUpload != null)
            {
                // tdata.ExecuteCommand("truncate table OtherCompanyAssets");  
                if (FileUpload.ContentType == "application/vnd.ms-excel" || FileUpload.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                {
                    string filename = FileUpload.FileName;
                    //string targetpath = Server.MapPath("~/Files/Excel/");
                    string targetpath = "D:/MassMail/ImportFiles/";
                    FileUpload.SaveAs(targetpath + filename);
                    string pathToExcelFile = targetpath + filename;
                    var connectionString = "";
                    if (filename.EndsWith(".xls"))
                    {
                        connectionString = string.Format("Provider=Microsoft.Jet.OLEDB.4.0; data source={0}; Extended Properties=Excel 8.0;", pathToExcelFile);
                    }
                    else if (filename.EndsWith(".xlsx"))
                    {
                        connectionString = string.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=\"Excel 12.0 Xml;HDR=YES;IMEX=1\";", pathToExcelFile);
                    }

                    var adapter = new OleDbDataAdapter("SELECT * FROM [Sheet1$]", connectionString);
                    var ds = new DataSet();

                    adapter.Fill(ds, "ExcelTable");

                    DataTable dtable = ds.Tables["ExcelTable"];

                    string sheetName = "Sheet1";

                    var excelFile = new ExcelQueryFactory(pathToExcelFile);
                    var dataExcel = from a in excelFile.Worksheet<DistributorModel>(sheetName) select a;
                    List<Contact> Contacts = new List<Contact>();

                    foreach (var item in dataExcel)
                    {
                        try
                        {
                            if (item.Code != "")
                            {
                                var TU = db.Distributors.FirstOrDefault(x => x.Code == item.Code);
                                if (TU == null)
                                {
                                    TU = new DistributorModel();
                                    TU.Name = item.Name;
                                    TU.Address = item.Address;
                                    TU.Code = item.Code;
                                    TU.AdminMail = item.AdminMail;
                                    TU.SEMail = item.SEMail;
                                    TU.AcMail = item.AcMail;
                                    TU.ManagerMail = item.ManagerMail;
                                    TU.Region = item.Region;
                                    TU.State = true;
                                    db.Distributors.Add(TU);
                                }
                                else
                                {
                                    TU.Name = item.Name;
                                    TU.Address = item.Address;
                                    TU.Code = item.Code;
                                    TU.AdminMail = item.AdminMail;
                                    TU.SEMail = item.SEMail;
                                    TU.AcMail = item.AcMail;
                                    TU.ManagerMail = item.ManagerMail;
                                    TU.Region = item.Region;
                                    TU.State = true;

FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Distributors/Create.cshtml
@model FCV_DutchLadyMail_Model.Models.DistributorModel

@{
    ViewBag.Title = "Create Distributor";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <style type="text/css">

        table {
            /*word-wrap: break-word;*/
             width: 100%;
        }
        .form-control {
            font-size:13px;
            padding:0px;
        }
        td p {
            margin-bottom: 0px;
        }
        .text_NPP {
            width: 36.36%;
            float: left;
            padding-top: 6px;
        }
        .input_NPP {
            width: 63.63%;
            float: left;
        }
    @@media screen and (max-width:767px) {
        .input_NPP {
            width: 63.63% !important;
            float: left;
        }

        .text_NPP {
            width: 36.36% !important;
            float: left;
            padding-top: 6px;
        }
    }
      

        .form-control {
            height: 28px;
            padding: 1px;
        }
       

    </style>
    <script src="~/Scripts/multiple-select.js"></script>
    <link rel="stylesheet" href="~/Content/custom/multiple-select.css" />
}

<div class="container" style="padding-top: 10px; width: 100%">
    @using (Html.BeginForm("Create", "Distributors", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Dis's Code</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Dis's Name</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Manager Email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.ManagerMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Admin's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.AdminMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>SE NPP's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.SEMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Ac's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.AcMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Region</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.DropDownListFor(model => model.Region, (SelectList)ViewBag.Region, new { id = "nppRegion",@style="width:30%;height:30px", @class = "form-control input-md ms-choice-focus", @placeholder = "Ac's email" })
                            @*<script>
                                $(function () {
                                    $('#nppRegion').multipleSelect({
                                        width: '100%',
                                        autoOpen: true,
                                        isOpen: false,
                                        keepOpen: false,
                                        placeholder: "Region"
                                    });
                                });
                            </script>*@
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                @*<div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <span>Active</span>
                        </div>
                        <div>
                            @Html.CheckBoxFor(model => model.State.Value, htmlAttributes: new { Name = "IsChecked", @style = "width:20px;height:20px;", @id = "ckeContent" })
                        </div>
                    </div>
                </div>*@
                <hr class="colorgraph">
                <div class="row">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Go to Distributors List", "Index", new { @controller = "Distributors" }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
    <div class="col-md-12" style="padding-bottom:10px">
        

    </div>
</div>

FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Distributors/Edit.cshtml
@model FCV_DutchLadyMail_Model.Models.DistributorModel

@{
    ViewBag.Title = "Edit Distributor";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <style type="text/css">
        table {
            /*word-wrap: break-word;*/
            width: 100%;
        }

        .form-control {
            font-size: 13px;
            padding: 0px;
        }

        td p {
            margin-bottom: 0px;
        }

        .text_NPP {
            width: 36.36%;
            float: left;
            padding-top: 6px;
        }

        .input_NPP {
            width: 63.63%;
            float: left;
        }

        @@media screen and (max-width:767px) {
            .input_NPP {
                width: 63.63% !important;
                float: left;
            }

            .text_NPP {
                width: 36.36% !important;
                float: left;
                padding-top: 6px;
            }
        }


        .form-control {
            height: 28px;
            padding: 1px;
        }
    </style>
    <script src="~/Scripts/multiple-select.js"></script>
    <link rel="stylesheet" href="~/Content/custom/multiple-select.css" />
}

<div class="container" style="padding-top: 10px; width: 100%">
    @using (Html.BeginForm("Edit", "Distributors", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Dis's Code</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Dis's Name</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Manager Email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.ManagerMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Admin's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.AdminMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>SE Dis's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.SEMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Ac's email</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.AcMail, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Region</label>
                        </div>
                        <div class="input_NPP form-group">
                            
                            @if (Model.Region == null)
                            {
                               @Html.DropDownListFor(model => model.Region, (SelectList)ViewBag.Region, new { id = "nppRegion", @style = "width:30%;height:30px", @class = "form-control input-md ms-choice-focus" })
                            }
                            else
                            {
                                var s = Model.Region.ToString();
                                <input type="hidden" value="@s" id="selectedF" />
                                @Html.DropDownListFor(model => model.Region, (SelectList)ViewBag.Region, new { id = "nppRegion", @style = "width:30%;height:30px", @class = "form-control input-md ms-choice-focus" })
                                @*@Html.DropDownList("Folders", null, new { @class = "form-control ", id = "folderSelect" })*@
                                <script>
                                    $("document").ready(function () {
                                        $('#nppRegion').val($('#selectedF').val());
                                    });
                                </script>
                            }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="input_NPP form-group">
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control input-md" })
                        </div>
                    </div>
                </div>
                @*<div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="col-sm-3 col-md-3">
                            <span>Active</span>
                        </div>
                        <div>
                            @if (Model.State == null)
                            {
                                Model.State = false;
                            }
                            else
                            { Model.State = true; }
                               
                            @Html.CheckBoxFor(model => model.State.Value, htmlAttributes: new { Name = "IsChecked", @style = "width:20px;height:20px;", @id = "ckeContent" })
                        </div>
                    </div>
                </div>*@
                <hr class="colorgraph">
                <div style="padding-bottom:10px">
                    <input type="submit" value="Update" class="btn btn-primary" />
                    @Html.ActionLink("Go to Distributors List", "Index", new { @controller = "Distributors" }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
    <div class="col-md-12" style="padding-bottom:10px">


    </div>
</div>

FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Distributors/_GetListSearchDis.cshtml
@model IEnumerable<FCV_DutchLadyMail_Model.Models.DistributorsView>
<link rel="stylesheet" href="~/Content/lib/data-table/dataTables.bootstrap.min.css" />
<script src="~/Content/js/lib/datatables/jquery.dataTables.min.js"></script>
<script src="~/Content/js/lib/datatables/dataTables.bootstrap.min.js"></script>
<script src="~/Content/custom/ColReorderWithResize.js"></script>

<div id="Preview" class="table-responsive" data-pattern="priority-columns">
    <table class="table table-bordered table-hover" border="0" width="100%" cellpadding="0" cellspacing="0" id="npp-table">
        <caption class="text-center">Distributors List</caption>
        <thead>
            <tr>
                <th class="table-header-repeat line-left minwidth-1" style="min-width: 45px; color: #000; font-size: 13px;width: 45px;">Code</th>
                <th class="table-header-repeat line-left minwidth-1" style="min-width: 100px; color: #000; font-size: 13px; width: 100px;">Name</th>
                <th class="table-header-repeat line-left minwidth-1" style="min-width: 55px; color: #000; font-size: 13px;">Region</th>
                <th class="table-header-repeat line-left minwidth-1" style="min-width: 160px; color: #000; font-size: 13px; width: 160px; ">Address</th>
                <th class="table-header-repeat line-left minwidth-1" style="min-width: 50px; color: #000; font-size: 13px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @{int i = 1;}
            @foreach (var item in Model)
            {
                <tr id="row_@item.ID">

                    <td class="row_2">
                        <span>@item.Code</span>

                    </td>
                    <td class="row_3">
                        <span>@item.Name</span>
                    </td>
                    <td class="row_4 table-header-repeat line-left minwidth-1">
                        @item.Regions.Name

                    </td>
                    <td class="row_9">
                        @item.Address
                    </td>
                    <td style="width: 47px;">
                        <center>
                            <a href="@Url.Action("Edit", "Distributors", new { id = item.ID })" class="fa fa-edit" style="color: black; font-size: 18px" title="Edit Distributor"></a>
                            <a href="@Url.Action("Delete", "Distributors", new { id = item.ID })" title="Delete Distributor" class="fa fa-trash-o" style="color: black; font-size: 18px" onclick="return confirm('are you sure you wish to remove this item?');"></a>
                        </center>
                    </td>
                </tr>
            }
        </tbody>

    </table>

</div>



   <script>

       $("#checkAll").change(function () {
           $("input.ckDis:checkbox").prop('checked', $(this).prop("checked"));
       });

       var t = $('#npp-table').DataTable({
           "dom": 'Rlfrtip',
            "bAutoWidth": false,
            "scrollX": true,
            "language": {
                "search": "Quick filter records:",
                "columnDefs": [{
                    "searchable": false,
                    "orderable": false,
                    "targets": 0
                }],
             "order": [[1, 'asc']]

            }
        });
       t.on('order.dt search.dt', function () {
           t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
               cell.innerHTML = i + 1;
           });
       }).draw();

       $(".collapse.in").each(function () {
           $(this).siblings(".panel-heading").find(".glyphicon").addClass("glyphicon-minus").removeClass("glyphicon-plus");
       });

       // Toggle plus minus icon on show hide of collapse element
       $(".collapse").on('show.bs.collapse', function () {
           $(this).parent().find(".glyphicon").removeClass("glyphicon-plus").addClass("glyphicon-minus");
       }).on('hide.bs.collapse', function () {
           $(this).parent().find(".glyphicon").removeClass("glyphicon-minus").addClass("glyphicon-plus");
       });

    </script>