Update of FCV_DutchLadyMail/FCV_DutchLadyMail/FCV_DutchLadyMail/Controllers/SignaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FCV_DutchLadyMail_Model.Models;
using PagedList;
using System.Data.Entity;
using System.Net.Mail;
using FCV_DutchLadyMail_Model.Attribute;
using FCV_DutchLadyMail_Model.Common;

namespace FCV_DutchLadyMail.Controllers
{

    public class SignaturesController : BaseController
    {
        private MassMailsDbContext db = new MassMailsDbContext();
        //
        // GET: /Signatures/

        public ActionResult Index(string searchString, string currentFilter, int page = 1, int pageSize = 10)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var _list = from l in db.Signatures select l;
            if (!String.IsNullOrEmpty(searchString))
            {
                _list = _list.Where(s => s.Name.Contains(searchString));
            }
            return View(_list.ToList().ToPagedList(page, pageSize));
        }

        public ActionResult Details(string id)
        {
            Signatures temp = db.Signatures.Find(int.Parse(id));

            return View("Details", temp);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Signatures sig)
        {

            if (sig != null && ModelState.IsValid)
            {
                var Identity = (IdentityUser)Session["Identity"];
                sig.UserID = Identity.UserName;
                sig.UpdateTime = DateTime.Now.ToString();
                db.Signatures.Add(sig);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View();

        }

        public ActionResult Edit(int id)
        {

            var sig = db.Signatures.Where(m => m.ID == id).Single();
            return View(sig);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(Signatures sig)
        {
            sig.UpdateTime = DateTime.Now.ToString();
            db.Entry(sig).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            db.Signatures.Remove(db.Signatures.Find(id));
            db.SaveChanges(); 
            
            return RedirectToAction("Index");
        }


    }
}

Update of FCV_DutchLadyMail/FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Signatures/Create.cshtml
@model FCV_DutchLadyMail_Model.Models.Signatures
@{
    ViewBag.Title = "Create Signature";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/ckeditor/ckeditor.js"></script>
}



@using (Html.BeginForm("Create", "Signatures", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })



        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Contents, htmlAttributes: new { @class = "form-control", @id = "ckeContent" })
                <script type="text/javascript">
                    CKEDITOR.replace("ckeContent",
                                {
                                    height: 130,
                                    language: 'en',
                                    image_previewText: " ",
                                    removePlugins: "help"

                                });
                </script>
            </div>
        </div>
        <hr class="colorgraph">
        <div style="padding-bottom:10px">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Go to Signatures List", "Index", new { @controller = "Signatures" }, new { @class = "btn btn-danger" })
        </div>
    </div>
}

Update of FCV_DutchLadyMail/FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Signatures/Details.cshtml
@model FCV_DutchLadyMail_Model.Models.Signatures

@{
    ViewBag.Title = "Signatures Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <style>
        hr {
             margin-top: 0; 
             margin-bottom: 0; 
            border: 0;
            border-top: 1px solid #eee;
        }
    </style>
}
<div class="container" style="padding-top: 10px; width: 100%;">
    
    <div class="row">
        <div class="col-6 col-md-2">
            <span>Name</span>
        </div>
        <div class="col-12 col-md-8 form-group">
            @Model.Name

        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-6 col-md-2">
            <span>Contents</span>
        </div>
        <div class="col-12 col-md-8 form-group">
            @MvcHtmlString.Create(Model.Contents)
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-6 col-md-2">
            <span>Created By</span>
        </div>
        <div class="col-12 col-md-8 form-group">
            @Model.UserID

        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-6 col-md-2">
            <span>Created Time</span>
        </div>
        <div class="col-12 col-md-8 form-group">
            @Model.UpdateTime
        </div>
    </div>
    
    <hr />
    <div class="col-md-12" style="padding-bottom:10px; padding-left:0px;padding-top:20px">
        @Html.ActionLink("Go to Signatures List", "Index", new { controller = "Signatures" }, new { @class = "btn btn-danger" })
    </div>
</div>

Update of FCV_DutchLadyMail/FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Signatures/Edit.cshtml
@model FCV_DutchLadyMail_Model.Models.Signatures
@{
    ViewBag.Title = "Edit Signature";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/ckeditor/ckeditor.js"></script>
}



@using (Html.BeginForm("Edit", "Signatures", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.UserID, new { @class = "control-label col-md-2" })

        <div class="row">
            <label class="col-md-2 control-label">Created By</label>
            <div class="col-md-10" style="padding-top:7px;">
                 <span>@Model.UserID</span>
            </div>
        </div>
        <div class="row">
            <label class="col-md-2 control-label">Last Update Time</label>
            <div class="col-md-10" style="padding-top:7px;">
                <span>@Model.UpdateTime</span>
            </div>
        </div>

        <div class="form-group" style="padding-top:7px;">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Contents, htmlAttributes: new { @class = "form-control", @id = "ckeContent" })
                <script type="text/javascript">
                    CKEDITOR.replace("ckeContent",
                                {
                                    height: 130,
                                    language: 'en',
                                    image_previewText: " ",
                                    removePlugins: "help"

                                });
                </script>
            </div>
        </div>


        <hr />
        <div style="padding-bottom:10px">
            <input type="submit" value="Update" class="btn btn-primary" />
            @Html.ActionLink("Go to Signatures List", "Index", new { @controller = "Signatures" }, new { @class = "btn btn-danger" })
        </div>
    </div>
}

Update of FCV_DutchLadyMail/FCV_DutchLadyMail/FCV_DutchLadyMail/Views/Signatures/Index.cshtml
@model IEnumerable<FCV_DutchLadyMail_Model.Models.Signatures>
@{
    ViewBag.Title = "Signatures Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link rel="stylesheet" href="~/Content/lib/data-table/dataTables.bootstrap.min.css" />
    <script src="~/Content/js/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/js/lib/datatables/dataTables.bootstrap.min.js"></script>
     <script src="~/Content/custom/ColReorderWithResize.js"></script>
    <style type="text/css">

        .table-responsive[data-pattern="priority-columns"] > .table > thead > tr > th, .table-responsive[data-pattern="priority-columns"] > .table > tbody > tr > th, .table-responsive[data-pattern="priority-columns"] > .table > tfoot > tr > th, .table-responsive[data-pattern="priority-columns"] > .table > thead > tr > td, .table-responsive[data-pattern="priority-columns"] > .table > tbody > tr > td, .table-responsive[data-pattern="priority-columns"] > .table > tfoot > tr > td {
            min-width: 20px;
            max-width: 500px;
            white-space: normal;
        }
        div.dataTables_wrapper div.dataTables_filter input {
            margin-left: 0.5em;
             display: inline-block; 
            width: 300px;
        }
        .sticky-table-header.fixed-solution {
            min-width: 0;
            position: fixed;
            height: 0px !important;
        }
    </style>
}

<div class="col-12">
    <div class="card">
        <div class="card-body">
            <div class="card-content">
                <div style="margin-bottom:30px">
                    @Html.ActionLink("Create New", "Create", new { @controller = "Signatures" }, new { @class = "btn btn-primary" }) 
                </div>
                <table class="table table-bordered table-hover" border="1" width="100%" cellpadding="0" cellspacing="0" id="data_table">
                    <caption class="text-center">Signatures List</caption>
                    <thead>
                        <tr>
                            <th></th>
                            <th style="min-width:40%">
                                Name
                            </th>
                            <th>
                                Create By
                            </th>
                            <th style="min-width:20%">
                                Last Update Time
                            </th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td></td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserID)
                                </td>
                                <td >
                                    @Html.DisplayFor(modelItem => item.UpdateTime)
                                </td>
                                <td style="width: 47px;">
                                    <center>
                                        <a href="@Url.Action("Edit", "Signatures", new { id = item.ID })" class="fa fa-edit" style="color: black; font-size: 18px" title="Edit Signature"></a>
                                        <a href="@Url.Action("Delete", "Signatures", new { id = item.ID })" title="Delete Signature" class="fa fa-trash-o" style="color: black; font-size: 18px" onclick="return confirm('are you sure you wish to remove this item?');"></a>
                                    </center>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
               

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var t = $('#data_table').DataTable({
        "dom": 'Rlfrtip',
        "bAutoWidth": true,
        "language": {
            "search": "Quick find:",
            "columnDefs": [{
                "searchable": false,
                "orderable": false,
                "targets": 0
            }],
            "order": [[1, 'asc']]

        }
    });
    t.on('order.dt search.dt', function () {
        t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
            cell.innerHTML = i + 1;
        });
    }).draw();

    $(".collapse.in").each(function () {
        $(this).siblings(".panel-heading").find(".glyphicon").addClass("glyphicon-minus").removeClass("glyphicon-plus");
    });

    // Toggle plus minus icon on show hide of collapse element
    $(".collapse").on('show.bs.collapse', function () {
        $(this).parent().find(".glyphicon").removeClass("glyphicon-plus").addClass("glyphicon-minus");
    }).on('hide.bs.collapse', function () {
        $(this).parent().find(".glyphicon").removeClass("glyphicon-minus").addClass("glyphicon-plus");
    });
</script>